# ROS2 Control configuration for Meca500
controller_manager:
  ros__parameters:
    update_rate: 200  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    position_controller:
      type: position_controllers/JointGroupPositionController


# Joint State broadcaster
joint_state_broadcaster:
  ros__parameters:
    type: joint_state_broadcaster/JointStateBroadcaster
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6


# Joint Trajectory Controller
joint_trajectory_controller:
  ros__parameters:
    type: joint_trajectory_controller/JointTrajectoryController
    group_name: meca500_arm         
    allow_integration_in_goal_trajectories: false
    allow_partial_joints_goal: false
    cmd_timeout: 0.0
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    interpolation_method: splines
    open_loop_control: false


# Joint Group Position Controller
position_controller:
  ros__parameters:
    type: position_controllers/JointGroupPositionController
    group_name: meca500_arm  
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6
