# Default initial positions for mitsubishi_robot's ros2_control fake system
# Author: Garrison Johnston 12/2025
initial_positions:
  joint1: 0.0
  joint2: 0.0
  joint3: 0.0
  joint4: 0.0
  joint5: 0.0
  joint6: 0.0
