# See the robot user manual table 7

# Author: Garrison Johnston 12/2025

# For beginners, we downscale velocity and acceleration limits.
# You can always specify higher scaling factors (<= 1.0) in your motion requests.  # Increase the values below to 1.0 to always move at maximum speed.
default_velocity_scaling_factor: 0.1
default_acceleration_scaling_factor: 0.1

joint_limits:
  joint1:
    has_velocity_limits: true
    max_velocity: 2.61799 # 150 deg/s
    has_acceleration_limits: true
    max_acceleration: 5.0
  joint2:
    has_velocity_limits: true
    max_velocity: 2.61799 # 150 deg/s 
    has_acceleration_limits: true
    max_acceleration: 5.0
  joint3:
    has_velocity_limits: true
    max_velocity: 3.14159 # 180 deg/s
    has_acceleration_limits: true
    max_acceleration: 5.0
  joint4:
    has_velocity_limits: true
    max_velocity: 5.23599 # 300 deg/s
    has_acceleration_limits: true
    max_acceleration: 5.0
  joint5:
    has_velocity_limits: true
    max_velocity: 5.23599 # 300 deg/s
    has_acceleration_limits: true
    max_acceleration: 5.0
  joint6:
    has_velocity_limits: true
    max_velocity: 8.72665 # 500 deg/s
    has_acceleration_limits: true
    max_acceleration: 5.0