# Limits for the Pilz planner

# Author: Garrison Johnston 12/2025
cartesian_limits:
  max_trans_vel: 5.0 # see page 42 of hardware manual
  max_trans_acc: 2.25
  max_trans_dec: -5.0
  max_rot_vel: 1.57
